// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// ledpanel //
// -------- //

#define ledpanel_wrap_target 2
#define ledpanel_wrap 10

static const uint16_t ledpanel_program_instructions[] = {
    0xb0cb, //  0: mov    isr, !null      side 4     
    0x5079, //  1: in     null, 25        side 4     
            //     .wrap_target
    0xa026, //  2: mov    x, isr          side 0     
    0x7a0b, //  3: out    pins, 11        side 6 [2] 
    0x1043, //  4: jmp    x--, 3          side 4     
    0x642b, //  5: out    x, 11           side 1     
    0x642b, //  6: out    x, 11           side 1     
    0xa342, //  7: nop                    side 0 [3] 
    0xa342, //  8: nop                    side 0 [3] 
    0xa342, //  9: nop                    side 0 [3] 
    0x0047, // 10: jmp    x--, 7          side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ledpanel_program = {
    .instructions = ledpanel_program_instructions,
    .length = 11,
    .origin = -1,
};

static inline pio_sm_config ledpanel_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ledpanel_wrap_target, offset + ledpanel_wrap);
    sm_config_set_sideset(&c, 3, false, false);
    return c;
}
#endif

