// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// tester //
// ------ //

#define tester_wrap_target 0
#define tester_wrap 2

static const uint16_t tester_program_instructions[] = {
            //     .wrap_target
    0xb042, //  0: nop                    side 0     
    0xa042, //  1: nop                               
    0xb842, //  2: nop                    side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program tester_program = {
    .instructions = tester_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config tester_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + tester_wrap_target, offset + tester_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

