// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// two_p_one_f_1 //
// ------------- //

#define two_p_one_f_1_wrap_target 0
#define two_p_one_f_1_wrap 3

static const uint16_t two_p_one_f_1_program_instructions[] = {
            //     .wrap_target
    0xf900, //  0: set    pins, 0         side 1 [1] 
    0xb042, //  1: nop                    side 0     
    0xa642, //  2: nop                           [6] 
    0x0000, //  3: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program two_p_one_f_1_program = {
    .instructions = two_p_one_f_1_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config two_p_one_f_1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + two_p_one_f_1_wrap_target, offset + two_p_one_f_1_wrap);
    sm_config_set_sideset(&c, 2, true, true);
    return c;
}
#endif

// ------------- //
// two_p_one_f_2 //
// ------------- //

#define two_p_one_f_2_wrap_target 0
#define two_p_one_f_2_wrap 3

static const uint16_t two_p_one_f_2_program_instructions[] = {
            //     .wrap_target
    0xf800, //  0: set    pins, 0         side 1     
    0xa742, //  1: nop                           [7] 
    0xb042, //  2: nop                    side 0     
    0x0000, //  3: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program two_p_one_f_2_program = {
    .instructions = two_p_one_f_2_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config two_p_one_f_2_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + two_p_one_f_2_wrap_target, offset + two_p_one_f_2_wrap);
    sm_config_set_sideset(&c, 2, true, true);
    return c;
}
#endif

