// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define D0 2
#define A0 10
#define RD 18
#define WR 19
#define DIR 20
#define OE 21

// -------- //
// Z80_read //
// -------- //

#define Z80_read_wrap_target 0
#define Z80_read_wrap 9

static const uint16_t Z80_read_program_instructions[] = {
            //     .wrap_target
    0xe002, //  0: set    pins, 2                    
    0x00c1, //  1: jmp    pin, 1                     
    0x4010, //  2: in     pins, 16                   
    0x8020, //  3: push   block                      
    0xc000, //  4: irq    nowait 0                   
    0x80a0, //  5: pull   block                      
    0x6008, //  6: out    pins, 8                    
    0xe000, //  7: set    pins, 0                    
    0x03c0, //  8: jmp    pin, 0                 [3] 
    0x0008, //  9: jmp    8                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program Z80_read_program = {
    .instructions = Z80_read_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config Z80_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + Z80_read_wrap_target, offset + Z80_read_wrap);
    return c;
}
#endif

// --------- //
// Z80_write //
// --------- //

#define Z80_write_wrap_target 0
#define Z80_write_wrap 7

static const uint16_t Z80_write_program_instructions[] = {
            //     .wrap_target
    0xe002, //  0: set    pins, 2                    
    0x00c1, //  1: jmp    pin, 1                     
    0xe000, //  2: set    pins, 0                    
    0x4010, //  3: in     pins, 16                   
    0x8020, //  4: push   block                      
    0xc001, //  5: irq    nowait 1                   
    0x03c0, //  6: jmp    pin, 0                 [3] 
    0x0006, //  7: jmp    6                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program Z80_write_program = {
    .instructions = Z80_write_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config Z80_write_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + Z80_write_wrap_target, offset + Z80_write_wrap);
    return c;
}
#endif

